### ISSUE TITLE
"download" not working

### ISSUE THREAD

**Issue by ghost** [shoonia/1x1#11]
https://shoonia.github.io/1x1/

When you click the "download" button, nothing happens. so it doesn't download the pixel.

https://ibb.co/KwH9YBG

**Comment by shoonia** [comment]
Hello @ghost 👋 
May you share more info about your device and browser? For example your user agent, like:

`Mozilla/5.0 (Linux; Android 12; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36
`
https://www.whatismybrowser.com/detect/what-is-my-user-agent/

It's needed to debug a functional.
